language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit

notifications:
  irc:   "irc.freenode.org#vespolina"
  
matrix:
  allow_failures:
    - php: hhvm
